import './styles/main.css'

import { 
  ArrowLeft,
  ArrowRight,
  ArrowDown,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowUp,
  ArrowUpLeft,
  ArrowUpRight,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Check,
  ChessKnight,
  Code,
  CodeXml,
  Download,
  DraftingCompass,
  EllipsisVertical,
  Expand,
  ExternalLink,
  Eye,
  EyeClosed,
  Grip,
  GripHorizontal,
  GripVertical,
  HatGlasses,
  Leaf,
  LeafyGreen,
  Link,
  Mail,
  Moon,
  MousePointer,
  Palette,
  Pilcrow,
  Rose,
  Scroll,
  Sliders,
  SlidersHorizontal,
  SlidersVertical,
  Star,
  SwatchBook,
  Terminal,
  X 
} from 'lucide'

const icon = X({ size: 16, strokeWidth: 1.5 })
document.querySelector('#some-element').appendChild(icon)